name = "belate"
main = "src/index.ts"
compatibility_date = "2026-09-14"

[[d1_databases]]
binding = "DB"
database_name = "belate"
database_id = "2946b1a8-3027-4a20-8d37-06cddf95059c"
migrations_dir = "migrations"

[triggers]
crons = ["* * * * *"]

# LIFF_ID is public and may be moved here instead of storing it as a secret.
# [vars]
# LIFF_ID = "YOUR_LIFF_ID"
