ALTER TABLE groups ADD COLUMN base_fine INTEGER NOT NULL DEFAULT 200 CHECK (base_fine >= 0);
ALTER TABLE groups ADD COLUMN per_min INTEGER NOT NULL DEFAULT 50 CHECK (per_min >= 0);
ALTER TABLE groups ADD COLUMN max_fine INTEGER NOT NULL DEFAULT 3000 CHECK (max_fine >= 0);
