export function liffHtml(liffId: string): string {
  const safeId = JSON.stringify(liffId).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BeLate</title>
  <style>body{font-family:system-ui,sans-serif;max-width:560px;margin:auto;padding:24px;background:#f5f7f6;color:#18201c}main{background:white;padding:22px;border-radius:16px;box-shadow:0 4px 20px #0001}button,input{font:inherit;padding:12px;margin:5px 0;width:100%;box-sizing:border-box}button{border:0;border-radius:9px;background:#06c755;color:white;font-weight:700}button.secondary{background:#52605a}label{display:block;margin-top:10px}#status{white-space:pre-wrap;margin:14px 0}.hidden{display:none}</style>
  </head><body><main><h1>BeLate</h1><div id="status">読み込み中…</div><section id="report" class="hidden"><button id="arrive">位置情報で到着報告</button><button id="share" class="secondary">現在地との距離だけ共有</button><button id="manual" class="secondary">位置が取れないので手動申告</button></section>
  <form id="settings" class="hidden"><label>集合日時<input id="meet" type="datetime-local" required></label><label>初期金額<input id="base" type="number" min="0" required></label><label>1分あたり<input id="per" type="number" min="0" required></label><label>上限<input id="max" type="number" min="0" required></label><button>設定を保存</button></form></main>
  <script src="https://static.line-scdn.net/liff/edge/2/sdk.js"></script><script>
  const LIFF_ID=${safeId}, qs=new URLSearchParams(location.search), eventId=qs.get('e'), mode=qs.get('mode')||'arrive'; let profile,eventData;
  const status=document.querySelector('#status'), report=document.querySelector('#report'), settings=document.querySelector('#settings');
  async function json(url,opts){const r=await fetch(url,opts),j=await r.json();if(!r.ok)throw Error(j.error||'通信エラー');return j}
  async function init(){try{await liff.init({liffId:LIFF_ID});if(!liff.isLoggedIn()){liff.login();return}if(!liff.isInClient())throw Error('LINEアプリ内から開いてください');profile=await liff.getProfile();eventData=await json('/api/events/'+encodeURIComponent(eventId));
    if(mode==='settings'){settings.classList.remove('hidden');document.querySelector('#meet').value=new Date(eventData.meetAt+32400000).toISOString().slice(0,16);document.querySelector('#base').value=eventData.baseFine;document.querySelector('#per').value=eventData.perMin;document.querySelector('#max').value=eventData.maxFine;status.textContent='幹事用の詳細設定';}
    else{report.classList.remove('hidden');status.textContent=eventData.placeName+' / '+new Date(eventData.meetAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'});}
  }catch(e){status.textContent=e.message}}
  function auth(){return {idToken:liff.getIDToken(),displayName:profile.displayName}}
  function locate(arrive){status.textContent='位置情報を取得中…';navigator.geolocation.getCurrentPosition(async p=>{try{const j=await json('/api/arrive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId,...auth(),lat:p.coords.latitude,lng:p.coords.longitude,arrive})});status.textContent=j.message+'\nあなたへのダウト: 遅刻する '+j.doubtProgress.predictsLate+' / 全'+j.doubtProgress.total;}catch(e){status.textContent=e.message}},e=>status.textContent='位置情報を取得できません: '+e.message,{enableHighAccuracy:true,timeout:15000})}
  document.querySelector('#arrive').onclick=()=>locate(true);document.querySelector('#share').onclick=()=>locate(false);document.querySelector('#manual').onclick=async()=>{if(!confirm('グループ内で確認する手動到着申告を送りますか？'))return;try{const j=await json('/api/arrive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId,...auth(),arrive:true,manual:true})});status.textContent=j.message}catch(e){status.textContent=e.message}};
  settings.onsubmit=async e=>{e.preventDefault();try{const j=await json('/api/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({eventId,userId:profile.userId,meetAt:new Date(document.querySelector('#meet').value+'+09:00').getTime(),baseFine:+document.querySelector('#base').value,perMin:+document.querySelector('#per').value,maxFine:+document.querySelector('#max').value})});status.textContent=j.message}catch(e){status.textContent=e.message}};init();</script></body></html>`;
}
